### ISSUE TITLE
Most titles per platform out of order.

### ISSUE THREAD

**Issue by pjmicolet** [Lifebar/support#16]
Maybe I'm missing something but currently my list of most titles per platform is out of order.
![untitled](https://cloud.githubusercontent.com/assets/1353391/12359292/8a7f3cae-bba9-11e5-875e-18fa55ecc32a.png)

**Comment by rewphus** [comment]
Yeah, it looks like you are right.  And thanks so much for the screenshots, those are super helpful.  We'll take a look in to it.

**Comment by rewphus** [comment]
This should be corrected now.  it was originally ordered first by color, and then by percentage complete, so since 76/200 was a higher percentage than 83/241, it was listed first, but now we simply have it listed by #, which I think is more intuitive.  Let us know if you see something else that looks out of place.
